version: '2.1'

services:
  vocbench3:
    container_name: vocbench3
    image: internetofwater/vocbench3:latest
    environment:     
      - JAVA_MAX_MEM=512M
    volumes:
      - ./vocbench_data:/app/vocbench3/data
    ports:
      - 1979:1979
    
  rdf4j:
    container_name: rdf4j
    image: datlowedocker/rdf4j:2.4.4
    environment:     
      - JVM_PARAMS=-Xmx2g
      - SESAME_PASS=change_it
      - RDF4J_DATA=/opt/rdf4j_data
    volumes:
      - ./rdf4j_data:/opt/rdf4j_data
    ports:
      - 8082:8082
    
